using System.Text;

namespace ExcelTool.CodeGen;

/// <summary>
/// 生成运行时共享的 BinaryTypeReader.cs。
/// 读取规则与 Export/BinaryTypeCodec 完全对称，供各 XxxTable.Load 使用。
/// 类型不变时内容固定，每轮导表覆盖写入即可。
/// </summary>
public static class BinaryTypeReaderGenerator
{
    public static void Generate(string outputDir, string namespaceName)
    {
        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, "BinaryTypeReader.cs");
        File.WriteAllText(outputPath, BuildSource(namespaceName), Encoding.UTF8);
    }

    private static string BuildSource(string namespaceName) =>
        $$"""
        // <auto-generated> 此文件由 ExcelTool 自动生成，请勿手动修改。
        // 与工具端 Export/BinaryTypeCodec 的类型 ID 与编码规则保持一致。

        using System.IO;
        using System.Text;

        namespace {{namespaceName}};

        /// <summary>
        /// XTBL v1 二进制读取器：解析 .bytes 文件头并按类型 ID 读取字段值。
        /// 各 XxxTable 在 Load 时调用本类，避免每张表重复实现读逻辑。
        /// </summary>
        public static class BinaryTypeReader
        {
            /// <summary>文件魔数，与 BinaryExporter 写入的 "XTBL" 一致。</summary>
            public const string Magic = "XTBL";

            /// <summary>当前支持的文件版本号。</summary>
            public const ushort Version = 1;

            /// <summary>
            /// 读取并校验 XTBL 文件头，返回行数与每列类型 ID。
            /// </summary>
            /// <param name="reader">已打开的二进制读取器，位置应在文件开头。</param>
            /// <returns>rowCount：数据行数；colTypes：每列类型 ID（与 Excel ##var 列顺序一致）。</returns>
            public static (int rowCount, byte[] colTypes) ReadHeader(BinaryReader reader)
            {
                var magicBytes = reader.ReadBytes(4);
                var magic = Encoding.ASCII.GetString(magicBytes);
                if (magic != Magic)
                    throw new InvalidDataException($"不是有效的配置表文件，Magic 应为 {Magic}，实际为 {magic}。");

                var version = reader.ReadUInt16();
                if (version != Version)
                    throw new InvalidDataException($"不支持的配置表版本: {version}，当前仅支持 {Version}。");

                var rowCount = reader.ReadInt32();
                var colCount = reader.ReadByte();
                var colTypes = new byte[colCount];
                for (var i = 0; i < colCount; i++)
                    colTypes[i] = reader.ReadByte();

                return (rowCount, colTypes);
            }

            /// <summary>
            /// 按类型 ID 读取单个字段值。类型 ID 见导表工具文档 / exceltool-types.mdc。
            /// </summary>
            public static object ReadValue(BinaryReader reader, byte typeId) => typeId switch
            {
                1 => reader.ReadUInt32(),
                2 => ReadString(reader),
                3 => reader.ReadSingle(),
                4 => reader.ReadInt32(),
                5 => reader.ReadInt64(),
                6 => reader.ReadDouble(),
                7 => reader.ReadBoolean(),
                11 => ReadIntArray(reader),
                12 => ReadUIntArray(reader),
                13 => ReadFloatArray(reader),
                14 => ReadStringArray(reader),
                15 => ReadLongArray(reader),
                16 => ReadBoolArray(reader),
                _ => throw new NotSupportedException($"未知的二进制类型 ID: {typeId}"),
            };

            /// <summary>string：int32 长度 + UTF-8 字节。</summary>
            public static string ReadString(BinaryReader reader)
            {
                var len = reader.ReadInt32();
                if (len == 0)
                    return "";
                return Encoding.UTF8.GetString(reader.ReadBytes(len));
            }

            /// <summary>数组：int32 元素个数 + 各 int。</summary>
            public static int[] ReadIntArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new int[count];
                for (var i = 0; i < count; i++)
                    arr[i] = reader.ReadInt32();
                return arr;
            }

            /// <summary>数组：int32 元素个数 + 各 uint。</summary>
            public static uint[] ReadUIntArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new uint[count];
                for (var i = 0; i < count; i++)
                    arr[i] = reader.ReadUInt32();
                return arr;
            }

            /// <summary>数组：int32 元素个数 + 各 long。</summary>
            public static long[] ReadLongArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new long[count];
                for (var i = 0; i < count; i++)
                    arr[i] = reader.ReadInt64();
                return arr;
            }

            /// <summary>数组：int32 元素个数 + 各 float。</summary>
            public static float[] ReadFloatArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new float[count];
                for (var i = 0; i < count; i++)
                    arr[i] = reader.ReadSingle();
                return arr;
            }

            /// <summary>数组：int32 元素个数 + 各 string。</summary>
            public static string[] ReadStringArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new string[count];
                for (var i = 0; i < count; i++)
                    arr[i] = ReadString(reader);
                return arr;
            }

            /// <summary>数组：int32 元素个数 + 各 bool。</summary>
            public static bool[] ReadBoolArray(BinaryReader reader)
            {
                var count = reader.ReadInt32();
                var arr = new bool[count];
                for (var i = 0; i < count; i++)
                    arr[i] = reader.ReadBoolean();
                return arr;
            }
        }
        """;
}
