using System.Text;
using ExcelTool.Models;

namespace ExcelTool.CodeGen;

/// <summary>
/// 根据本轮导出的全部表，生成 GameConfigTables.cs 全局入口。
/// 表增删后重新导表即可自动更新属性与 Initialize 逻辑。
/// </summary>
public static class GlobalTablesGenerator
{
    public const string ClassName = "GameConfigTables";

    public static void Generate(IReadOnlyList<TableData> tables, string outputDir, string namespaceName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 此文件由 ExcelTool 自动生成，请勿手动修改。");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using BaseLayer.ConfigTable;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        CodeGenHelper.AppendNamespaceOpen(sb, namespaceName);
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 配置表全局入口：聚合所有 XxxTable，提供一次性 Initialize。");
        sb.AppendLine("/// Unity 启动时在 Awake 调用 Initialize，业务通过 Instance 访问各表。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {ClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>初始化完成后的全局单例。Initialize 之前为 null。</summary>");
        sb.AppendLine($"    public static {ClassName} Instance {{ get; private set; }}");
        sb.AppendLine();

        foreach (var table in tables)
        {
            var tableClass = CodeGenHelper.ToTableClassName(table.Name);
            sb.AppendLine($"    /// <summary>{table.Name} 表访问器。</summary>");
            sb.AppendLine($"    public {tableClass} {table.Name} {{ get; }} = new {tableClass}();");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 从目录加载全部 .bytes（路径拼接 {表名}.bytes）。");
        sb.AppendLine("    /// 适用于 Editor 直读、StreamingAssets 等场景。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void Initialize(string dataDir)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var t = new {ClassName}();");
        foreach (var table in tables)
        {
            sb.AppendLine($"        t.{table.Name}.Load(Path.Combine(dataDir, \"{table.Name}.bytes\"));");
        }
        sb.AppendLine("        Instance = t;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 从预加载的字节字典解析全部表（AssetBundle 两阶段加载的第二阶段）。");
        sb.AppendLine("    /// 字典键支持 \"Hero.bytes\" 或 \"Hero\"（TextAsset 名常无扩展名）。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void Initialize(IReadOnlyDictionary<string, byte[]> tableBytes)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var t = new {ClassName}();");
        foreach (var table in tables)
        {
            sb.AppendLine($"        t.{table.Name}.Load(RequireBytes(tableBytes, \"{table.Name}\"));");
        }
        sb.AppendLine("        Instance = t;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>按表名从预加载字典取 bytes，兼容带/不带 .bytes 后缀的键。</summary>");
        sb.AppendLine("    static byte[] RequireBytes(IReadOnlyDictionary<string, byte[]> tableBytes, string tableName)");
        sb.AppendLine("    {");
        sb.AppendLine("        byte[] data;");
        sb.AppendLine("        if (tableBytes.TryGetValue(tableName + \".bytes\", out data))");
        sb.AppendLine("            return data;");
        sb.AppendLine("        if (tableBytes.TryGetValue(tableName, out data))");
        sb.AppendLine("            return data;");
        sb.AppendLine("        throw new KeyNotFoundException(\"预加载字典中找不到表 [\" + tableName + \"] 的 bytes。\");");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>向 BaseLayer 注册 bytes 解析入口；导表后随本类一并生成。</summary>");
        sb.AppendLine("    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.SubsystemRegistration)]");
        sb.AppendLine("    static void RegisterToFramework()");
        sb.AppendLine("    {");
        sb.AppendLine("        ConfigTableInitRegistry.Register(Initialize);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        CodeGenHelper.AppendNamespaceClose(sb);

        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{ClassName}.cs");
        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }
}
