using System.Text;
using ExcelTool.Models;

namespace ExcelTool.CodeGen;

/// <summary>
/// 根据 TableData 生成 {Name}Table.cs：Load 二进制 + 按主键 GetByMainID。
/// 主键约定：第一列字段名 id，类型由 ##type 决定。
/// </summary>
public static class TableCodeGenerator
{
    public static void Generate(TableData table, string outputDir, string namespaceName)
    {
        var tableClass = CodeGenHelper.ToTableClassName(table.Name);
        var metaClass = CodeGenHelper.ToMetaClassName(table.Name);
        var mainKeyColumn = table.Columns[0];
        var mainKeyField = CodeGenHelper.ToPascalCase(mainKeyColumn.Name);
        var mainKeyType = CodeGenHelper.ToCSharpType(mainKeyColumn.Type);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated> 此文件由 ExcelTool 自动生成，请勿手动修改。");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.IO;");
        sb.AppendLine("using BaseLayer.GameUtils;");
        sb.AppendLine();
        CodeGenHelper.AppendNamespaceOpen(sb, namespaceName);
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {table.Name} 配置表访问类。");
        sb.AppendLine($"/// 职责：加载 {table.Name}.bytes，构建主键索引，提供 GetByMainID 查询。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {tableClass}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>主键 → 行数据。第一列 [{mainKeyColumn.Name}] 作为键。</summary>");
        sb.AppendLine($"    readonly Dictionary<{mainKeyType}, {metaClass}> _byMainId = new Dictionary<{mainKeyType}, {metaClass}>();");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>从磁盘路径加载（Editor 调试或非 AB 场景）。</summary>");
        sb.AppendLine("    public void Load(string filePath)");
        sb.AppendLine("    {");
        sb.AppendLine("        using (var stream = File.OpenRead(filePath))");
        sb.AppendLine("            Load(stream);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>从内存字节加载（AssetBundle TextAsset.bytes 等）。</summary>");
        sb.AppendLine("    public void Load(byte[] data) => Load(new MemoryStream(data));");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 从流解析 XTBL 二进制，填充 _byMainId。");
        sb.AppendLine("    /// 列顺序与 Excel ##var 行一致，类型 ID 见 BaseLayer.GameUtils.BinaryTypeIds。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public void Load(Stream stream)");
        sb.AppendLine("    {");
        sb.AppendLine("        _byMainId.Clear();");
        sb.AppendLine("        using (var xtbl = XtblBinaryReader.Open(stream))");
        sb.AppendLine("        {");
        sb.AppendLine("            var colTypes = xtbl.Header.ColumnTypes;");
        sb.AppendLine("            for (var r = 0; r < xtbl.Header.RowCount; r++)");
        sb.AppendLine("            {");
        sb.AppendLine($"                var row = new {metaClass}();");
        sb.AppendLine("                ReadRow(xtbl, colTypes, row);");
        sb.AppendLine($"                _byMainId[row.{mainKeyField}] = row;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>按主键取一行，不存在时抛 KeyNotFoundException。</summary>");
        sb.AppendLine($"    public {metaClass} GetByMainID({mainKeyType} mainId)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {metaClass} row;");
        sb.AppendLine("        if (_byMainId.TryGetValue(mainId, out row))");
        sb.AppendLine("            return row;");
        sb.AppendLine($"        throw new KeyNotFoundException(\"[{table.Name}] 不存在 mainId=\" + mainId);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>按主键尝试取一行，不存在返回 false。</summary>");
        sb.AppendLine($"    public bool TryGetByMainID({mainKeyType} mainId, out {metaClass} row)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _byMainId.TryGetValue(mainId, out row);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>只读访问全部行（遍历用）。</summary>");
        sb.AppendLine($"    public IReadOnlyCollection<{metaClass}> All => _byMainId.Values;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>按导出时的列顺序，从流中读取一行并赋给 Meta 字段。</summary>");
        sb.AppendLine($"    static void ReadRow(XtblBinaryReader reader, byte[] colTypes, {metaClass} row)");
        sb.AppendLine("    {");

        for (var i = 0; i < table.Columns.Count; i++)
        {
            var column = table.Columns[i];
            var field = CodeGenHelper.ToPascalCase(column.Name);
            var csType = CodeGenHelper.ToCSharpType(column.Type);
            sb.AppendLine($"        row.{field} = ({csType})reader.ReadField(colTypes[{i}]);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        CodeGenHelper.AppendNamespaceClose(sb);

        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{tableClass}.cs");
        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }
}
